require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - bin/**
    - db/**/*
    - config/puma.rb

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods:
    - context
    - describe
    - let
